### ISSUE TITLE
Running the Bebop_Loiter_INDI_Simple

### ISSUE THREAD

**Issue by ardalanghadimi** [iff-gsc/LADAC-Examples#4]
Hi, Hope you all are doing well.
thank you for all your efforts for this repository.

I cloned the LADAC and installed and test as the readme stated, and all items Passed in check_ladac, I also check the Joystick performance as mentioned in Test Joystick.

but for running the Bep2_loiter_INDI_Simple, got the below error in the simulation stage after compiling Simulink. could you please check whether I did something wrong?

it works in "model('QuadcopterSimModel_LindiCopter')" and connects to FG truly  but for this "model('QuadcopterSimModel_INDI_Loiter_simple')" I got the attached error:
I changed the Simulation sample time but still not working.
![Error](https://user-images.githubusercontent.com/40306965/210963531-4eaf9d62-bc48-4cb0-a70a-9336c635d811.png)
![Passed](https://user-images.githubusercontent.com/40306965/210963546-29594758-79ff-4e7b-9a4f-cd6468849499.png)

Thank you for considering.

**Comment by ybeyer** [comment]
Hi, thank very much for the bug report. I was not aware of the problem.
The problem should now be fixed.
Just update LADAC-Examples and try it again.
