### ISSUE TITLE
Issue Encountered While Implementing Guidance

### ISSUE THREAD

**Issue by iXiaoxideYan** [iff-gsc/LADAC-Examples#6]
Thank you sincerely for your contributions to this repository. I've encountered an issue while following your instructions. The error message is as follows:

Warning: No joystick with ID 1 connected! Running 'HebiJoystick Input' with dummy outputs!
Invalid setting in 'QuadcopterSimModel_LindiCopter/INDI Controller/Constant1' for parameter 'Value'.
Caused by:
Error evaluating parameter 'Value' in 'QuadcopterSimModel_LindiCopter/INDI Controller/Constant1'
Unrecognized field name "traj".
Component:Simulink | Category:Block error

Could you please provide some guidance on resolving this issue? Thank you for your assistance.

**Comment by ybeyer** [comment]
Hi, which `init_...` file did you run to initialize the parameters for the Simulink model?
Could you try to initialize the model with the following file? `Copter/Minnie/init_quadcopter_Minnie_LindiCopter.m`

**Comment by iXiaoxideYan** [comment]
> Hi, which `init_...` file did you run to initialize the parameters for the Simulink model? Could you try to initialize the model with the following file? `Copter/Minnie/init_quadcopter_Minnie_LindiCopter.m`

Dear,

Thank you for your reply. It is indeed the script that I am running. And I notice that in the workspace, there is no lindi.traj.wpmax but I find lindi_notune.traj.wpmax which is the input for QuadcopterSimModel_LindiCopter/INDI Controller/Constant1. 

And After I replace lindi.traj.wpmax with lindi_notune.traj.wpmax, the quadcopter just hovering in place. Can you please provide guidance on what to do to get the drone in motion? Is it because I'm not giving him input?

<img width="501" alt="image" src="https://github.com/iff-gsc/LADAC-Examples/assets/59574706/4657f027-d81c-4436-baf7-c9bfd852a0fc">

Best regards,
Yan
